/**
 * Application bootstrap.
 * Called on every start.
 *
 * - Ensures Public role has read-only permissions for all content types.
 * - First-run init marker is set once.
 */

interface PermissionConfig {
  uid: string
  actions: string[]
}

/** Content types to expose via Public API (find + findOne). */
const PUBLIC_READ_CONTENT_TYPES: PermissionConfig[] = [
  { uid: 'api::site.site', actions: ['find', 'findOne'] },
  { uid: 'api::category.category', actions: ['find', 'findOne'] },
  { uid: 'api::product.product', actions: ['find', 'findOne'] },
  { uid: 'api::page.page', actions: ['find', 'findOne'] },
  { uid: 'api::global.global', actions: ['find', 'findOne'] },
  { uid: 'api::blog.blog', actions: ['find', 'findOne'] },
  { uid: 'api::news.news', actions: ['find', 'findOne'] },
  { uid: 'api::site-layout.site-layout', actions: ['find', 'findOne'] },
  { uid: 'api::keyword-cluster.keyword-cluster', actions: ['find', 'findOne'] },
  { uid: 'api::tag.tag', actions: ['find', 'findOne'] },
  { uid: 'api::faq.faq', actions: ['find', 'findOne'] },
  { uid: 'api::author.author', actions: ['find', 'findOne'] },
  { uid: 'api::organization.organization', actions: ['find', 'findOne'] },
]

export async function bootstrap() {
  await setupPublicPermissions()
  await syncProductViewConfig()
  await syncTagViewConfig()
  await syncPageStatusField()
  await markFirstRun()
}

async function setupPublicPermissions() {
  try {
    const publicRole = await strapi
      .documents('plugin::users-permissions.role')
      .findFirst({
        filters: { type: 'public' },
      })

    if (!publicRole) {
      strapi.log.warn('[Bootstrap] Public role not found — skipping permission setup.')
      return
    }

    const roleDocumentId = (publicRole as Record<string, unknown>).documentId as string

    for (const config of PUBLIC_READ_CONTENT_TYPES) {
      for (const action of config.actions) {
        const actionName = `${config.uid}.${action}`

        // Check if permission already exists to keep idempotent.
        const existing = await strapi
          .documents('plugin::users-permissions.permission')
          .findFirst({
            filters: {
              action: actionName,
              role: { documentId: roleDocumentId },
            },
          })

        if (!existing) {
          await strapi.documents('plugin::users-permissions.permission').create({
            data: {
              action: actionName,
              role: { documentId: roleDocumentId },
            },
          })
          strapi.log.info(`[Bootstrap] Granted: ${actionName}`)
        }
      }
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)
    strapi.log.error(`[Bootstrap] Permission setup failed: ${message}`)
  }
}

/**
 * Strapi 5 does not automatically sync schema pluginOptions.content-manager
 * to the stored view configuration. This function patches the stored config
 * so that auto-generated / system-managed fields stay hidden in the admin UI.
 */
async function syncProductViewConfig() {
  const UID = 'api::product.product'
  const HIDDEN_FIELDS = ['sku', 'status', 'tags_json_deprecated']

  try {
    const cmService = strapi.plugin('content-manager').service('content-types')
    const config = await cmService.findConfiguration({ uid: UID })
    if (!config?.layouts?.edit) return // config not yet generated by Strapi

    let changed = false

    // 1. Hide in metadata
    for (const field of HIDDEN_FIELDS) {
      const meta = config.metadatas?.[field]
      if (meta) {
        if (meta.edit?.visible !== false) { meta.edit.visible = false; changed = true }
        if (meta.list?.searchable !== false) { meta.list.searchable = false; changed = true }
        if (meta.list?.sortable !== false) { meta.list.sortable = false; changed = true }
      }
    }

    // 2. Remove from edit layout
    config.layouts.edit = config.layouts.edit
      .map((row: any[]) => row.filter((col: any) => !HIDDEN_FIELDS.includes(col.name)))
      .filter((row: any[]) => row.length > 0)

    // 3. Remove from list layout
    config.layouts.list = config.layouts.list.filter(
      (col: string) => !HIDDEN_FIELDS.includes(col),
    )

    if (changed) {
      await cmService.updateConfiguration({ uid: UID }, config)
      strapi.log.info('[Bootstrap] Product view config synced — hidden: sku, status')
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    strapi.log.warn(`[Bootstrap] Product view config sync failed: ${msg}`)
  }
}

/**
 * Configure Tag slug field: visible but read-only (auto-generated by lifecycle).
 */
async function syncTagViewConfig() {
  const UID = 'api::tag.tag'
  const READONLY_FIELDS = ['slug']

  try {
    const cmService = strapi.plugin('content-manager').service('content-types')
    const config = await cmService.findConfiguration({ uid: UID })
    if (!config?.layouts?.edit) return // config not yet generated by Strapi

    let changed = false

    // Set slug visible but non-editable
    for (const field of READONLY_FIELDS) {
      const meta = config.metadatas?.[field]
      if (meta) {
        if (meta.edit?.visible !== true) { meta.edit.visible = true; changed = true }
        if (meta.edit?.editable !== false) { meta.edit.editable = false; changed = true }
        if (meta.list?.searchable !== true) { meta.list.searchable = true; changed = true }
        if (meta.list?.sortable !== true) { meta.list.sortable = true; changed = true }
      }
    }

    // Hide the inverse side of self-referencing relatedtags (admin users only use `relatedtags`)
    const relatedFromMeta = config.metadatas?.['relatedFrom']
    if (relatedFromMeta?.edit?.visible !== false) {
      if (relatedFromMeta) {
        if (relatedFromMeta.edit) relatedFromMeta.edit.visible = false
        changed = true
      }
    }

    if (changed) {
      await cmService.updateConfiguration({ uid: UID }, config)
      strapi.log.info('[Bootstrap] Tag view config synced — slug visible, relatedFrom hidden')
    }
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    strapi.log.warn(`[Bootstrap] Tag view config sync failed: ${msg}`)
  }
}

/**
 * One-time migration: sync custom `status` field with Strapi 5's built-in
 * Draft & Publish (`publishedAt`) for all existing documents.
 *
 * Page, Blog, News, and Product schemas all have both `draftAndPublish`
 * (publishedAt) AND a custom `status` enumeration. Before lifecycle hooks
 * were added, publishing would set `publishedAt` but leave the custom
 * `status` at its default "draft". This migration fixes existing entries.
 */
const STATUS_SYNC_UIDS = [
  'api::page.page',
  'api::blog.blog',
  'api::news.news',
  'api::product.product',
  'api::author.author',
] as const

async function syncPageStatusField() {
  const PLUGIN_KEY = 'syncStatusField_v2'

  try {
    const pluginStore = strapi.store({
      environment: strapi.config.environment,
      type: 'type',
      name: 'setup',
    })

    const hasRun = await pluginStore.get({ key: PLUGIN_KEY })
    if (hasRun) return

    let totalFixed = 0

    for (const uid of STATUS_SYNC_UIDS) {
      // Fix: publishedAt is set but status is still "draft"
      const draftButPublished: any[] = await strapi.db
        .query(uid)
        .findMany({
          where: {
            $and: [
              { publishedAt: { $notNull: true } },
              { status: 'draft' },
            ],
          },
        })

      for (const entry of draftButPublished) {
        await strapi.db.query(uid).update({
          where: { id: entry.id },
          data: { status: 'published' },
        })
      }

      // Fix: publishedAt is null but status is "published"
      const publishedButDraft: any[] = await strapi.db
        .query(uid)
        .findMany({
          where: {
            $and: [
              { publishedAt: { $null: true } },
              { status: 'published' },
            ],
          },
        })

      for (const entry of publishedButDraft) {
        await strapi.db.query(uid).update({
          where: { id: entry.id },
          data: { status: 'draft' },
        })
      }

      if (draftButPublished.length > 0 || publishedButDraft.length > 0) {
        strapi.log.info(
          `[Migration] ${uid}: fixed ${draftButPublished.length} draft→published, ${publishedButDraft.length} published→draft`,
        )
        totalFixed += draftButPublished.length + publishedButDraft.length
      }
    }

    await pluginStore.set({ key: PLUGIN_KEY, value: true })
    strapi.log.info(
      `[Migration] syncStatusField complete — ${totalFixed} entries fixed across ${STATUS_SYNC_UIDS.length} content types`,
    )
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error)
    strapi.log.warn(`[Migration] syncStatusField failed: ${msg}`)
  }
}

async function markFirstRun() {
  const pluginStore = strapi.store({
    environment: strapi.config.environment,
    type: 'type',
    name: 'setup',
  })
  const initHasRun = await pluginStore.get({ key: 'initHasRun' })
  if (!initHasRun) {
    await pluginStore.set({ key: 'initHasRun', value: true })
    strapi.log.info('[B2B CMS] First run — no seed data imported.')
  }
}
